version: '3.2'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  datameta-client:

    build:
      context: .
      dockerfile: ./Dockerfile
    
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  datameta-app:
    image: "datameta/datameta:dev"
    environment:
      SQLALCHEMY_URL: postgresql://datameta:datameta@datameta-postgresql/datameta
      SQLALCHEMY_TEST_URL: postgresql://datameta:datameta@datameta-postgresql/test
      SESSION_URL: datameta-memcached:11211
      SESSION_KEY: datameta
      SESSION_SECRET: "test"
      DATAMETA_STORAGE_PATH: /var/datameta/storage
      DATAMETA_DEMO_MODE: "false"
      DATAMETA_INITIAL_FULLNAME: "admin"
      DATAMETA_INITIAL_EMAIL: "admin@admin.admin"
      DATAMETA_INITIAL_PASS: "admin"
      DATAMETA_INITIAL_GROUPNAME: "admin"
      WAITRESS_MAX_REQUEST_BODY_SIZE: 10737418240 # 10 GB
      WAITRESS_LISTEN: "*:8080"
      WAITRESS_URL_SCHEME:
      WAITRESS_TRUSTED_PROXY_HEADERS:
      WAITRESS_TRUSTED_PROXY:
    volumes:
      - type: volume
        source: datameta-filestorage
        target: /var/datameta/storage
        volume:
          nocopy: true
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode : dnsrr

  datameta-memcached:
    image: "memcached:1.6.3"
    command: ['memcached', '-v', '-m', '3072', '-I', '50m']
    deploy:
      endpoint_mode : dnsrr

  datameta-postgresql:
    image: "postgres:13-alpine"
    volumes:
      - type: volume
        source: datameta-db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      POSTGRES_USER: datameta
      POSTGRES_PASSWORD: datameta
    command: ['postgres', '-c', 'work_mem=512MB']
    deploy:
      endpoint_mode : dnsrr


volumes:
  datameta-db:
    external: false
  datameta-filestorage:
    external: false