FROM python:3.8

# install essential dependencies
RUN apt-get update -qq -y
RUN apt-get install -y \
    build-essential \
    postgresql-client \
    libmemcached-dev \
    gettext \
    nodejs \
    npm \
    less \
    git

RUN mkdir /workspace \
    && cd /workspace \
    && git clone https://github.com/ghga-de/datameta.git . \
    && cp ./docker/* /bin
